name: Deploy feature

on:
  push:
    branches:
      - 'feature-dev/**'
      - 'feature-test/**'

permissions:
  contents: read

jobs:
  define-feature-version:
    runs-on: ubuntu-latest
    outputs:
      feature_version: ${{ steps.get-feature-version.outputs.feature_version }}
    steps:
      - uses: actions/checkout@v6
      - uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/remove-prefix@v1
        id: get-feature-name
        with:
          string: ${{ github.ref_name }}
          prefix: 'feature-*/'
      - name: Get feature version
        id: get-feature-version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "feature_version=${{ steps.get-feature-name.outputs.result }}-${COMMIT_HASH}-SNAPSHOT" >> $GITHUB_OUTPUT
          echo "Feature version: ${{ steps.get-feature-name.outputs.result }}-${COMMIT_HASH}-SNAPSHOT"

  build-and-publish-snapshot:
    needs: [ define-feature-version ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      integration_test_task: "integrationTest"
      publish_package: 'true'
      override_version: ${{ needs.define-feature-version.outputs.feature_version }}
      junit_results_path: 'data-service/build/test-results'
      junit_report_path: 'data-service/build/reports/tests'
      checkstyle_report_path: 'data-service/build/reports/checkstyle'
      jacoco_coverage_report_path: 'data-service/build/reports/jacoco'
      java_version: '25'
      java_distribution: 'corretto'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  ecr-publish-image:
    needs: [ build-and-publish-snapshot ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      image_version: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.build-and-publish-snapshot.outputs.published_artifact_version) }}
      jar_subproject: 'data-service'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  update-helm-chart:
    needs: [ ecr-publish-image ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/update-helm-chart.yml@v1
    with:
      helm_charts_repository: 'laa-ccms-caab-helm-charts'
      helm_charts_branch: 'development'
      service_name: 'laa-ccms-caab-service'
      subchart_name: 'caab-ebs-api'
      application_version: ${{ needs.ecr-publish-image.outputs.published_image_version }}
      feature_branch: ${{ github.ref_name }}
      github_bot_username: 'laa-ccms-caab-service'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ vars.LAA_CCMS_CAAB_SERVICE_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_CCMS_CAAB_SERVICE_KEY }}
      github_app_organisation: 'ministryofjustice'
